### ISSUE TITLE
Add toString() to Id Classes 

### ISSUE THREAD

**Issue by upachler** [gentity/gentity#35]
Currently, Id classes do not have a `toString()` method. This method is important, because persistence providers may report errors on object Ids and call `toString()` to print the object identity.

The goal is to _extend_ the gentity code generator to generate `toString()` methods for an entity's `Id` class. Such a method should print the the content of all fields of the `Id` class instance. The output should be human readable (as this `toString()` implementation is intended for debugging) and take the form of key-value pairs. The output should be similar to JSON, but not JSON.
For Example:
For an class `MyEntity.Id` like this:
```java
class MyEntity {
...
  class Id {
    int parentNumber;
    String groupName;
    ...
  }
...
}
```

So with parentNumber=24 and parentGroup='foo', `toString()` should print
`MyEntity$Id{parentNumber=24, parentGroup="foo"}`

**Comment by TawfikYasser** [comment]
Kindly point to the file need changes.

**Comment by upachler** [comment]
@TawfikYasser: I guess that'd be Generator.java in the core package. There is a spot where the `equals()` and `hashCode()` methods are generated for the `Id` class, and that's where `toString()` should go.

**Comment by maharana0299** [comment]
What you wanna print when toString() method is called ?

**Comment by upachler** [comment]
To clarify:
The goal is to _extend_ the gentity code generator to generate `toString()` methods for an entity's `Id` class. See the updated description above.
